### PR TITLE
kurashiki-wapuu add

### PR DESCRIPTION
**Pull request by 466548**
倉敷公式わぷーを追加しました。よろしくお願いします。

### CODE REVIEW

**Comment by miya0001** [comment]
What is the `466548` in your data?

Anyway, this repository has been seeing by non Japanese speaker.
Please write in English too.

**Comment by miya0001** [comment]
Please fix following too.

**Comment by 466548** [comment]
I'm very sorry.Kurashiki Official Wapuu has been added.

**Comment by 466548** [comment]
I'm sorry, I made modifications.

**Comment by miya0001** [comment]
Hi, please check your line in CSV again. 😄 

The data in `description` field is `466548 466548`.
It should be `WordBench Kurashiki Wapuu` or so.
And line ending should be added to this line.

Thanks. 😄

**Comment by 466548** [comment]
Sorry frequently:sob:
description fixed.

**Comment by miya0001** [comment]
Do you need `466548` in description?

**Comment by 466548** [comment]
Excuse me. The author got permission from Kurashiki organizer to put my name I made. I will fix it again. I'm sorry.

**Comment by miya0001** [comment]
If you want to add your name and your URL, there are `author.name` and `author.url` fields in the CSV file.

Please see:
https://github.com/jawordpressorg/wapuu-api/blob/master/wapuu.csv

**Comment by 466548** [comment]
author.name and author.url fixed.I would like to apologize for my mistake.

**Comment by miya0001** [comment]
Thanks!

**Comment by 466548** [comment]
I am sorry in various ways. You're very kind.

**Pull request merged**
