### PR TITLE
Request to add new Wapuu to archive

### PR DESCRIPTION
**Pull request by ishimasar**
Nice to meet you!

### CODE REVIEW

**Comment by ishimasar** [comment]
Hello!
Please merge if possible!
We operate the Mitaka / Kichijoji WordPress Meetup in Tokyo, Japan.

Results of Activities

https://www.meetup.com/ja-JP/Tokyo-WordPress-Meetup/events/274080827/

https://www.meetup.com/ja-JP/Tokyo-WordPress-Meetup/events/269867870/

**Comment by mirucon** [comment]
@ishimasar I am sorry for the delay. I want you to make a quick change that to add `,image/png` just after the image URL? It looks like it's missing now. Once it's fixed I'll merge it.

**Comment by ishimasar** [comment]
@mirucon 
Thank you very much.
Added `image/png,`.

**Review by mirucon — APPROVED** [review]
Perfect! Thanks for adding your wapuu :)

**Pull request merged**
