### PR TITLE
Wapuu WordCamp Ahmedabad

### PR DESCRIPTION
**Pull request by parthpandya24**
Wapuu of WordCamp Ahmedabad info added in csv file

### CODE REVIEW

**Comment by mirucon** [comment]
Thanks for your PR @pandya-parth!  It seems like you have broken the CSV file, would you mind fixing that so we can merge your wapuu? And also the committer of the commit you made is somebody else. You would want to fix this as well. If you are not really sure on how to do it, I can do it so please let me know if you do or not :)

**Comment by parthpandya24** [comment]
Hello @mirucon 

Please fix it and change the committer to pandya-parth. 

Thanks

**Comment by mirucon** [comment]
Hi @pandya-parth,
Though I can fix the CSV file, changing the committer should be done by you as it's not something I can do easily. So please run the following commands in your repository and push your changes:

```bash
$ git -c user.name="New Author Name" -c user.email=email@address.com commit --reset-author --amend
$ git push origin master -f
```

**Comment by parthpandya24** [comment]
I have changed the author. Please fix CSV and publish wapuu

**Comment by mirucon** [comment]
Thanks, I've fixed and re-created PR in #52. Your wapuu will be added soon :)

**Pull request closed without merging**
