### PR TITLE
Joe A Simpson Jr Wapuu additions

### PR DESCRIPTION
**Pull request by joesimpsonjr**
Request to add these Wapuu to the official archive for Wapuu characters. 

Information on the six Wapuu creatures created to celebrate WordPress in Communities I've been involved with: 

- Accessipuu
- Bleepuu
- Prongaloop*
- Ragspuu
- Speedy*
- Tikipuu

* Prongaloop and Speedy Wapuu are already a part of the Wapuu.us collection.

### CODE REVIEW

**Comment by mirucon** [comment]
@joesimpsonjr Thanks for your pull request! Can you quote the descriptions with double or single quotes? Without quotes, the commas in your descriptions are recognized as separators for a column.

**Comment by joesimpsonjr** [comment]
@mirucon Quotes added as requested.

**Comment by mirucon** [comment]
@joesimpsonjr Ah sorry you also need to quote your name as it has a comma in it. And if you want to use GitHub for image URLs you'll have to add `?raw=1` at the end of the current URLs because https://github.com/joesimpsonjr/wapuu/blob/main/tikipuu-wapuu.png actually links to preview page and not an image itself. https://github.com/joesimpsonjr/wapuu/blob/main/tikipuu-wapuu.png?raw=1 would be the correct one.

**Comment by joesimpsonjr** [comment]
Additional clean up completed. Thanks, @mirucon and team for your patience.

**Comment by mirucon** [comment]
I'm really sorry I didn't realise this until now, but you need one simple change; you've mixed up the URLs of the third and fourth columns. In the third column, you should have the URL where your wapuu is used so it would be WordCamp or Meetup URL, and in the fourth, you should have the GitHub repository URL for your wapuu. So basically you have to swap these fields. Once it's fixed, I think it's good to go.

**Comment by joesimpsonjr** [comment]
@mirucon , let's try this one more time. URLs in the order requested. Thanks.

**Review by mirucon — APPROVED** [review]
Thanks so much for fixing it! Adding your wapuus to the archive.

**Pull request merged**
