### PR TITLE
wapuubha wordcamp ahmedabad

### PR DESCRIPTION
**Pull request by parthpandya24**

### CODE REVIEW

**Comment by miya0001** [comment]
Ah, could you please upload the image of the Wapuu to your own repository?

**Comment by parthpandya24** [comment]
Hello,

 

Its already there named wapuubha.png.

 

Here is the URL of it: https://raw.githubusercontent.com/KrishaWeb/wapuu-api/master/wapuubha.png

 

Thanks

**Comment by raftaar1191** [comment]
@pandya-parth 
Can you please resolve this conflicts?

**Comment by mirucon** [comment]
@pandya-parth If you would still like to add your wapuu in the archive, please delete the image from this PR and resolve the conflicts so that we can merge this PR.

**Comment by parthpandya24** [comment]
I have removed the image from the current PR.

**Comment by mirucon** [comment]
@pandya-parth Did you actually add your Wapuu in the latest commit? Seems you deleted it when you resolve the conflicts. Also I still see the image in your repo, make sure to remove that

**Pull request closed without merging**
