### PR TITLE
Duchess Roude Léiweli -- Wapuu for the Luxembourg community

### PR DESCRIPTION
**Pull request by stephanie-walter**
I created a new wapuu for the Luxembourgish community and wanted to add it to the official repository

### CODE REVIEW

**Comment by geoffreycrofte** [comment]
We need that one!

**Review by mirucon — COMMENTED** [review]
Hi there! Thanks for adding your Wapuu to this repository. You somehow added your Wapuu image in this repository, which is not necessary. Would you mind removing this file and the PR looks ready to go!

**Comment by stephanie-walter** [comment]
Ha sorry I didn't get any notification for your reply and forgot about it. I will remove it and let you know :)

**Review by mirucon — APPROVED** [review]
I've just removed the unnecessary image for you :) Adding your wapuu to the archives...

**Comment by stephanie-walter** [comment]
Haa thanks a lot!!!

**Pull request merged**
