### PR TITLE
NAPUU

### PR DESCRIPTION
**Pull request by ghost**
Official Mascot for WordCamp Nashik 2016

### CODE REVIEW

**Comment by miya0001** [comment]
I'm sorry for late reply.
But please add Wapuu information into CSV.
See following. Thanks!
https://github.com/jawordpressorg/wapuu-api#how-to-add-your-wapuu

**Comment by ghost** [comment]
Hi,
I've added the information to the CSV file
Thanks,
Harshad Mane
Lead Organizer
WordCamp Nashik 2016

**Comment by miya0001** [comment]
Please give me pull request for your CSV. 😄

**Comment by ghost** [comment]
My Bad
https://github.com/bornforlamp/wapuu-api/blob/master/wapuu.csv

**Pull request merged**
