### PR TITLE
edited for wapuu -wordcamp kanpur 2k17

### PR DESCRIPTION
**Pull request by shbhmdvd**
changes for kanpur wordcamp

### CODE REVIEW

**Comment by miya0001** [comment]
Oh, please edit,
https://github.com/jawordpressorg/wapuu-api/blob/master/wapuu.csv

**Comment by miya0001** [comment]
Ah,

* Yo broke the CSV, please check.
* Please upload the image of you Wapuu to your own repository.

**Comment by HardeepAsrani** [comment]
@shbhmdvd Can you do it, else I'll do it for you. Thanks!

**Comment by shbhmdvd** [comment]
I did it but i dont know what 's wrong if you can do it write then please
do it.

Regards .:
Shubham dwivedi

On 08-Nov-2017 6:53 PM, "Hardeep Asrani" <notifications@github.com> wrote:

@shbhmdvd <https://github.com/shbhmdvd> Can you do it, else I'll do it for
you. Thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jawordpressorg/wapuu-api/pull/38#issuecomment-342815987>,
or mute the thread

**Pull request closed without merging**
