### PR TITLE
Add Wapuussoa - WordCamp Lisboa 2019

### PR DESCRIPTION
**Pull request by pedro-mendonca**
https://2019.lisboa.wordcamp.org

### CODE REVIEW

**Comment by mirucon** [comment]
@pedro-mendonca Would you mind resolving the conflicts? It looks good to go once you fix the conflicts.

**Comment by pedro-mendonca** [comment]
Hi @mirucon 
Just rebasen on top of the last accepted PR and fixed the conflicts.
Thank you.

**Review by mirucon — APPROVED** [review]
Great, thanks!

**Comment by pedro-mendonca** [comment]
@mirucon what is the eta for it to get deployed to json and archive? Is it automatic?

**Comment by mirucon** [comment]
Well, it seems like the deploy is broken (it's automated though). Let me try to fix this.

**Comment by mirucon** [comment]
@pedro-mendonca I pushed a manual deploy because the automatic deploy fails. You can now see your wapuu in the archive!

**Comment by pedro-mendonca** [comment]
Great! Thank you.

**Pull request merged**
