### PR TITLE
Added Tuk-Tuk Wapuu

### PR DESCRIPTION
**Pull request by ChiakiKouno**
Added Tuk-Tuk Wapuu

### CODE REVIEW

**Review by mirucon — COMMENTED** [review]
Thanks for your PR!
There's one thing you need to change; your url field should be the raw image file, instead of a GitHub's preview page. So what you need to have for the url will be `https://raw.githubusercontent.com/ChiakiKouno/tuktuk-wapuu/master/tuktuk-wapuu.png`

**Comment by ChiakiKouno** [comment]
Thank you for your review and I'm sorry for the mistake! I will try again!

**Comment by ChiakiKouno** [comment]
I have changed it. Please kindly check it again, thank you!

**Review by mirucon — APPROVED** [review]
LGTM 👍

**Comment by ChiakiKouno** [comment]
It's my first merge!! Yay, thank you!

**Pull request merged**
